"""
Forecasting module SQLAlchemy models.
Maps to forecasts and alerts tables for Stage 2: Internal Intelligence.
"""

from __future__ import annotations

import enum
from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import ForeignKey, String, Date, Numeric, Boolean, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class AlertType(str, enum.Enum):
    """Types of intelligence alerts."""
    anomaly = "anomaly"
    reorder = "reorder"


class Severity(str, enum.Enum):
    """Alert severity levels."""
    info = "info"
    warning = "warning"
    critical = "critical"


class Forecast(Base):
    """Persisted SARIMA demand forecasts."""

    __tablename__ = "forecasts"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    station_id: Mapped[UUID] = mapped_column(ForeignKey("stations.id", ondelete="CASCADE"))
    fuel_type: Mapped[str] = mapped_column(String(20), nullable=False)
    forecast_date: Mapped[date] = mapped_column(Date, nullable=False)
    predicted_volume: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), default="sarima_v1")
    created_at: Mapped[datetime] = mapped_column(default=datetime.utcnow)


class Alert(Base):
    """Anomaly / reorder alerts generated by the intelligence engine."""

    __tablename__ = "alerts"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    station_id: Mapped[UUID] = mapped_column(ForeignKey("stations.id", ondelete="CASCADE"))
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="warning")
    fuel_type: Mapped[str | None] = mapped_column(String(20))
    message: Mapped[str] = mapped_column(Text, nullable=False)
    details: Mapped[dict | None] = mapped_column(JSON)
    is_resolved: Mapped[bool] = mapped_column(Boolean, default=False)
    resolved_at: Mapped[datetime | None] = mapped_column()
    resolved_by: Mapped[UUID | None] = mapped_column(ForeignKey("profiles.id"))
    created_at: Mapped[datetime] = mapped_column(default=datetime.utcnow)
